const DATA = [
  {
    id: 1,
    name: 'Garfield',
    caretaker: 'Jon Arbuckle',
    color: 'Orange',
    personality: 'Grumpy',
    petCount: 0,
  },
  {
    id: 2,
    name: 'Meowth',
    caretaker: 'Team Rocket',
    color: 'Cream',
    personality: 'Scheming',
    petCount: 0,
  },
  {
    id: 3,
    name: 'Hello Kitty',
    caretaker: 'Mama Kitty',
    color: 'White',
    personality: 'Sweet',
    petCount: 0,
  },
  {
    id: 4,
    name: 'Salem',
    caretaker: 'Sabrina Spellman',
    color: 'Black',
    personality: 'Snarky',
    petCount: 0,
  },
  {
    id: 5,
    name: 'Puss in Boots',
    caretaker: 'Shrek',
    color: 'Ginger',
    personality: 'Bold',
    petCount: 0,
  },
  {
    id: 6,
    name: 'Nyan Cat',
    caretaker: 'Internet',
    color: 'Rainbow',
    personality: 'Chaotic',
    petCount: 0,
  },
  {
    id: 7,
    name: 'Cheshire Cat',
    caretaker: 'Wonderland',
    color: 'Purple',
    personality: 'Mysterious',
    petCount: 0,
  },
  {
    id: 8,
    name: 'Marie',
    caretaker: 'Duchess',
    color: 'White',
    personality: 'Prim',
    petCount: 0,
  },
  {
    id: 9,
    name: 'Tigress',
    caretaker: 'Shifu',
    color: 'Orange',
    personality: 'Serious',
    petCount: 0,
  },
  {
    id: 10,
    name: 'Luna',
    caretaker: 'Usagi Tsukino',
    color: 'Black',
    personality: 'Wise',
    petCount: 0,
  }
];


export default DATA;
